apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-listener-deployment
  labels:
    app: dotnet-e2e-pubsub-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-e2e-pubsub-listener
  template:
    metadata:
      labels:
        app: dotnet-e2e-pubsub-listener
    spec:
      containers:
      - name: dotnet-e2e-pubsub-listener
        image: gcr.io/$PROJECT_ID/dotnet-e2e-trace-listener-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
