FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY pubsub-listener-service/*.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY pubsub-listener-service/. ./
RUN dotnet publish -c Release -o out

# Build runtime imag
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "PubSubListener.dll"]