FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY cloudrun-web-app/*.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY cloudrun-web-app/. ./
RUN dotnet publish -c Release -o out
#RUN dotnet publish -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "GoogleCloudSamples.EndToEndTracing.WebApp.dll"]